image: node:10.15.1

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

install_dependencies:
  stage: build
  script:
    - npm install
    - npm run lint
  artifacts:
    paths:
      - node_modules/
