image: node:10.15.1

stages:
  - build
  - test

cache:
  paths:
    - node_modules/

test:
  stage: build
  script:
    - npm install
    - npm run lint
    - npm run lint:fix
    - npm run format
  artifacts:
    paths:
      - node_modules/
